In [68]:
import pandas as pd
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='Column')
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [3]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [34]:
df['ConvertedComp'].median( )

57287.0

In [69]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [70]:
df['Hobbyist'].value_counts( normalize= True )*100

Hobbyist
Yes    80.169436
No     19.830564
Name: proportion, dtype: float64

In [71]:
df[ ['SocialMedia' ,  'EduOther'  , 'DevType']].head(50)

,SocialMedia,EduOther,DevType
Respondent,,,
1,Twitter,"Taught yourself a new language, framework, or ...",NaN
2,Instagram,Taken an online course in programming or softw...,"Developer, desktop or enterprise applications;..."
3,Reddit,"Taught yourself a new language, framework, or ...","Designer;Developer, back-end;Developer, front-..."
4,Reddit,Taken an online course in programming or softw...,"Developer, full-stack"
5,Facebook,Taken an online course in programming or softw...,"Academic researcher;Developer, desktop or ente..."
6,YouTube,Taken an online course in programming or softw...,Data or business analyst;Data scientist or mac...
7,YouTube,"Taught yourself a new language, framework, or ...","Designer;Developer, front-end"
8,YouTube,"Taught yourself a new language, framework, or ...","Developer, back-end;Engineer, site reliability"
9,Twitter,Taken an online course in programming or softw...,"Database administrator;Developer, back-end;Dev..."
10,YouTube,NaN,Data or business analyst;Data scientist or mac...
11,NaN,Contributed to open source software,NaN
12,Reddit,Taken an online course in programming or softw...,Data or business analyst;Data scientist or mac...
13,Twitter,Taken an online course in programming or softw...,Data or business analyst;Database administrato...
14,Reddit,Completed an industry certification program (e...,"Developer, desktop or enterprise applications"
15,YouTube,Taken an online course in programming or softw...,Student
16,YouTube,Taken an online course in programming or softw...,"Developer, full-stack"
17,YouTube,Taken an online course in programming or softw...,"Developer, back-end;Developer, front-end;Devel..."
18,VK ВКонта́кте,Taken an online course in programming or softw...,Data or business analyst
19,WhatsApp,Received on-the-job training in software devel...,"Developer, full-stack"
20,Facebook,Taken an online course in programming or softw...,"Database administrator;Designer;Developer, bac..."
21,I don't use social media,"Taught yourself a new language, framework, or ...",NaN
22,Instagram,Taken an online course in programming or softw...,"Data or business analyst;Designer;Developer, b..."
23,Reddit,Taken an online course in programming or softw...,"Developer, full-stack"
24,Reddit,Taken an online course in programming or softw...,"Developer, front-end"
25,YouTube,Taken an online course in programming or softw...,"Designer;Developer, back-end;Developer, front-..."
26,I don't use social media,"Taught yourself a new language, framework, or ...","Designer;Developer, back-end;Developer, deskto..."
27,YouTube,Taken an online course in programming or softw...,"Developer, back-end;Developer, front-end;Devel..."
28,Instagram,Taken an online course in programming or softw...,"Designer;Developer, front-end;Developer, full-..."
29,Reddit,Taken an online course in programming or softw...,"Developer, front-end;Educator"
30,YouTube,"Taught yourself a new language, framework, or ...","DevOps specialist;Engineer, site reliability"
31,YouTube,NaN,NaN
32,YouTube,Completed an industry certification program (e...,"Developer, full-stack"
33,WhatsApp,Taken an online course in programming or softw...,Academic researcher;Data scientist or machine ...
34,Facebook,Taken an online course in programming or softw...,"Developer, full-stack"
35,Instagram,Taken a part-time in-person course in programm...,"Developer, front-end"
36,Reddit,Taken an online course in programming or softw...,"Developer, mobile;Student"
37,Reddit,Taken a part-time in-person course in programm...,Student
38,I don't use social media,Participated in a full-time developer training...,"Developer, full-stack;Engineer, data"
39,Reddit,Taken an online course in programming or softw...,"Database administrator;Developer, back-end;Dev..."
40,Facebook,Taken an online course in programming or softw...,"Developer, back-end;Developer, full-stack;Student"
41,Facebook,Taken an online course in programming or softw...,"Developer, front-end;Student"
42,Facebook,Taken a part-time in-person course in programm...,Academic researcher;Data or business analyst;D...
43,WhatsApp,Taken an online course in programming or softw...,"Developer, front-end;Developer, game or graphi..."
44,Twitter,Taken an online course in programming or softw...,"Developer, back-end;Developer, desktop or ente..."
45,Facebook,Received on-the-job training in software devel...,Engineering manager
46,I don't use social media,Taken an online course in programming or softw...,"Developer, full-stack;Engineer, data"
47,Instagram,Taken an online course in programming or softw...,Engineering manager
48,VK ВКонта́кте,NaN,"Database administrator;Developer, back-end;Dev..."
49,I don't use social media,"Taught yourself a new language, framework, or ...","Database administrator;Developer, back-end;Dev..."
50,YouTube,Received on-the-job training in software devel...,"Developer, back-end;DevOps specialist"

In [52]:
df['SocialMedia'].value_counts( normalize = True )*100

SocialMedia
Reddit                      17.023343
YouTube                     16.379076
WhatsApp                    15.807051
Facebook                    15.606902
Twitter                     13.498822
Instagram                    7.414996
I don't use social media     6.577685
LinkedIn                     5.330602
WeChat 微信                    0.789938
Snapchat                     0.743750
VK ВКонта́кте                0.714142
Weibo 新浪微博                   0.066322
Youku Tudou 优酷               0.024871
Hello                        0.022502
Name: proportion, dtype: float64

In [72]:
country_grp = df.groupby(['Country'])

In [73]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [62]:
df['SocialMedia'].head(30)

Respondent
1                      Twitter
2                    Instagram
3                       Reddit
4                       Reddit
5                     Facebook
6                      YouTube
7                      YouTube
8                      YouTube
9                      Twitter
10                     YouTube
11                         NaN
12                      Reddit
13                     Twitter
14                      Reddit
15                     YouTube
16                     YouTube
17                     YouTube
18               VK ВКонта́кте
19                    WhatsApp
20                    Facebook
21    I don't use social media
22                   Instagram
23                      Reddit
24                      Reddit
25                     YouTube
26    I don't use social media
27                     YouTube
28                   Instagram
29                      Reddit
30                     YouTube
Name: SocialMedia, dtype: object

In [10]:
filt = df['Country']  == 'India'
df[filt]['SocialMedia'].value_counts()

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: count, dtype: int64

In [11]:
country_grp['SocialMedia'].value_counts(normalize = True ).loc['China']*100

SocialMedia
WeChat 微信                   67.054908
YouTube                      8.818636
Weibo 新浪微博                   6.988353
I don't use social media     4.492512
Twitter                      4.492512
Reddit                       1.996672
LinkedIn                     1.830283
Facebook                     1.331115
Instagram                    1.164725
Youku Tudou 优酷               1.164725
WhatsApp                     0.499168
VK ВКонта́кте                0.166389
Name: proportion, dtype: float64

In [12]:
country_grp['ConvertedComp'].median().loc['Germany']
# median salary in germany

63016.0

In [13]:
country_grp['ConvertedComp'].agg( [ 'mean' , 'median' , 'max' , 'min' ,'std' ]).loc[ [ 'Canada' , 'Germany'  , 'India']]

                  mean   median        max  min            std
Country
Canada   134018.564909  68705.0  2000000.0  0.0  229255.567850
Germany  109256.884066  63016.0  2000000.0  0.0  187384.595666
India     28057.664916  10080.0  2000000.0  0.0   85630.003577

In [16]:
country_grp['ConvertedComp'].loc['Germany']

63016.0

In [18]:
 country_grp.get_group(('Germany', ))['ConvertedComp']

Respondent
14        57060.0
36        20628.0
44        87996.0
66       137490.0
85        52704.0
           ...
64465         NaN
71055         NaN
75974         NaN
80319         NaN
83786         NaN
Name: ConvertedComp, Length: 5866, dtype: float64

In [43]:
filt = df['Country'] == 'India' 
df.loc[filt, 'LanguageWorkedWith'].str.contains('Python').sum()

36443

In [80]:
country_grp['LanguageWorkedWith'].apply( lambda x:x.str.contains('Python')).loc['India'].sum()

3105

In [75]:
country_respondents = df['Country'].value_counts()
country_respondents

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [81]:
df['Country']

Respondent
1                United Kingdom
2        Bosnia and Herzegovina
3                      Thailand
4                 United States
5                       Ukraine
                  ...
88377                    Canada
88601                       NaN
88802                       NaN
88816                       NaN
88863                     Spain
Name: Country, Length: 88883, dtype: object

In [90]:
country_python = country_grp['LanguageWorkedWith'].apply( lambda x : x.str.contains( 'Python').sum())
country_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [96]:
df2 = pd.concat( [country_respondents , country_python] , axis = 'columns' , sort = False )
df2

                   count  LanguageWorkedWith
Country
United States      20949               10083
India               9061                3105
Germany             5866                2451
United Kingdom      5737                2384
Canada              3395                1558
...                  ...                 ...
Tonga                  1                   0
Timor-Leste            1                   1
North Korea            1                   0
Brunei Darussalam      1                   0
Chad                   1                   0

[179 rows x 2 columns]

In [102]:
df2.rename(columns={'Country': 'NumRespondents', 'LanguageWorkedWith': 'NumKnowsPython'} , inplace = True )
df2

                   count  NumKnowsPython
Country
United States      20949           10083
India               9061            3105
Germany             5866            2451
United Kingdom      5737            2384
Canada              3395            1558
...                  ...             ...
Tonga                  1               0
Timor-Leste            1               1
North Korea            1               0
Brunei Darussalam      1               0
Chad                   1               0

[179 rows x 2 columns]

In [105]:
df2['percentknowpython'] = ( df2['NumKnowsPython']* 100  / df2['count']) 
df2

                   count  NumKnowsPython  percentknowpython
Country
United States      20949           10083          48.131176
India               9061            3105          34.267741
Germany             5866            2451          41.783157
United Kingdom      5737            2384          41.554820
Canada              3395            1558          45.891016
...                  ...             ...                ...
Tonga                  1               0           0.000000
Timor-Leste            1               1         100.000000
North Korea            1               0           0.000000
Brunei Darussalam      1               0           0.000000
Chad                   1               0           0.000000

[179 rows x 3 columns]

In [107]:
df2.sort_values( by = 'percentknowpython'  , ascending = False  )

                                  count  NumKnowsPython  percentknowpython
Country
Sao Tome and Principe                 1               1         100.000000
Timor-Leste                           1               1         100.000000
Dominica                              1               1         100.000000
Niger                                 1               1         100.000000
Turkmenistan                          7               6          85.714286
...                                 ...             ...                ...
Cape Verde                            3               0           0.000000
Lao People's Democratic Republic      3               0           0.000000
Malawi                                2               0           0.000000
Liberia                               2               0           0.000000
Chad                                  1               0           0.000000

[179 rows x 3 columns]

In [113]:
df2.loc[  : , "percentknowpython"].sort_values( )

Country
Chad                       0.000000
Tajikistan                 0.000000
Andorra                    0.000000
Burkina Faso               0.000000
Cape Verde                 0.000000
                            ...
Turkmenistan              85.714286
Sao Tome and Principe    100.000000
Niger                    100.000000
Dominica                 100.000000
Timor-Leste              100.000000
Name: percentknowpython, Length: 179, dtype: float64